### ISSUE TITLE
Bash Profile workaround

### ISSUE THREAD

**Issue by Cheffrey2000** [learn-co-curriculum/github-to-canvas#1]
In working to get this setup on my machine, I ran into an issue with setting up the credentials. I use bash and ran into issues trying to get it set up.  The solution I came up with is as follows:
Setting up the API:
`echo "$(export 'CANVAS_API_KEY=<your-new-API-key-here>' | cat  - ~/.zshrc)" > ~/.zshrc`
For bash Should be:
`echo 'export CANVAS_API_KEY=your-new-API-key-here' >>~/.bash_profile`

Adding the API path:
`echo "$(export 'CANVAS_API_PATH=<your-base-api-path>' | cat  - ~/.zshrc)" > ~/.zshrc`
For bash Should be:
`echo 'export CANVAS_API_PATH=your-base-api-path' >>~/.bash_profile`

once these are run, you must run `source ~/.bash_profile` for the changes to take effect.

**Comment by maxwellbenton** [comment]
Hi @Cheffrey2000,

Thank you for this feedback! I've updated the README to provide both command options along with more updated commands/options, which should resolve this issue.
