### ISSUE TITLE
Scrimba playlists breaking the github-to-canvas map function

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/github-to-canvas#5]
When creating a yml file using `github-to-canvas --query`, there's a line that contains only a hyphen representing each scrimba playlist. Then, when using `github-to-canvas --map` to map the yml file to a csv file, an "undefined method `[]' for nil:NilClass" error is thrown. It is necessary to hand-edit the yml file to remove all the stray hyphens before executing the map function.

**Comment by ihollander** [comment]
The culprit: https://github.com/learn-co-curriculum/github-to-canvas/blob/master/lib/github-to-canvas/canvas_interface.rb#L220-L222
